services:
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: appuser
      MYSQL_PASSWORD: changepass
      MYSQL_DATABASE: appdb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3399:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  openjdk:
    image: openjdk:17
    container_name: openjdk
    command: sleep infinity
    restart: unless-stopped

  web-html:
    image: nginx:alpine
    container_name: html-server
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8181:80"
    restart: unless-stopped